# Generated by Django 5.0.7 on 2024-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_value', models.BooleanField()),
                ('time_get', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='send_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_value', models.BooleanField()),
                ('time_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
