# Generated by Django 5.0.7 on 2024-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_information',
            name='send_value',
            field=models.BooleanField(default=False),
        ),
    ]
